UIDEXP-312: View All page displays export jobs in random order
folio-org/ui-data-export pull request #370
Opened 2023-04-26 07:09 UTC by UladzislauKutarkin

## Purpose

[UIDEXP-312](https://issues.folio.org/browse/UIDEXP-312)
## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-04-26 13:07 UTC, BogdanDenis requested changes

2023-04-27 06:50 UTC, UladzislauKutarkin commented on src/components/AllJobLogsView/AllJobLogsView.js
> +            shouldSetInitialSort={true}
Thanks @BogdanDenis , I just missed it

2023-04-27 06:52 UTC, UladzislauKutarkin commented on src/components/AllJobLogsView/CustomQueryBuilder.js
> +    const sortingDirection= key.startsWith('-') ? ASC_DIRECTION : ASC_ASCENDING;
Also good idea, forgot to rename it, since now we have to types of directions. I fixed that already

2023-04-27 07:54 UTC, BogdanDenis approved these changes

2023-04-27 10:25 UTC, vashjs approved these changes

2023-04-27 10:31 UTC, merged